# This is a basic workflow to help you get started with Actions

#name: CI

# Controls when the action will run. 
#on:
  # Triggers the workflow on push or pull request events but only for the main branch
 # push:
  #  branches: [ main ]
  #pull_request:
   # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
  # This workflow contains a single job called "build"
 # semgrep:
  #  runs-on: ubuntu-latest
   # name: Check
    #steps:
     # - uses: actions/checkout@v1
      #- name: Semgrep
       # id: semgrep
        #uses: returntocorp/semgrep-action@v1
